# -*- coding: utf-8 -*-
"""LoanSolvencyApp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iAG3VuwBJJxOnHnij5OfP-cJNuHbNV7h
"""

import pickle                                                         # Import pickle to read/load models
import streamlit as st                                                # Import web framework for the application
st.title("Loan Solvability Prediction")                               # Set the title of the interface
gender=st.selectbox("Gender",["Male","Female","Other"])
married=st.selectbox("Married",["Yes","No","Other"])
dependents=st.selectbox("Dependents",["0","1","2","3+","Other"])
education=st.selectbox("Education",["Graduate","Not Graduate","Other"])
self_employed=st.selectbox("Self Employed",["Yes","No","Other"])
applicant_income=st.number_input("Applicant Income")
coapplicant_income=st.number_input("Coapplicant Income")
loan_amount_term=st.number_input("Loan Amount Term")
credit_history=st.number_input("Credit History")
proparea=st.selectbox("Property Area",["Urban","Semi Urban","Rural"])
le_gender=pickle.load(open("le_gender.pickle","rb"))
le_married=pickle.load(open("le_married.pickle","rb"))
le_dependents=pickle.load(open("le_dependents.pickle","rb"))
le_education=pickle.load(open("le_education.pickle","rb"))
le_self_employed=pickle.load(open("le_self_employed.pickle","rb"))
le_proparea=pickle.load(open("le_property_area.pickle","rb"))
gender=le_gender.transform([gender])[0]
married=le_married.transform([married])[0]
dependents=le_dependents.transform([dependents])[0]
education=le_education.transform([education])[0]
self_employed=le_self_employed.transform([self_employed])[0]
proparea=le_proparea.transform([proparea])[0]
X=[[gender,married,dependents,education,self_employed,applicant_income,coapplicant_income,loan_amount_term,credit_history,proparea]]
model=pickle.load(open("model.pickle","rb"))
if st.button("Predict"):
    prediction=model.predict(X)
    st.success(prediction)